import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    padding: 16,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: '#f5f5f5',
    marginBottom: 5,
  },
  headerLogo: {
    width: 200,
    height: 60,
    marginLeft: -60,
  },
  headerAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: -10,
  },
  header: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#0A2458',
    marginVertical: 10,
    alignSelf: 'flex-start', 
    marginHorizontal: 15, 
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 8,
    backgroundColor: '#fff',
    fontSize: 13,
    marginHorizontal: 15, 
  },
  searchButton: {
    backgroundColor: '#405F90',
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 5,
    marginHorizontal: 15, 
  },
  searchButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  card: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    marginBottom: 12,
    marginHorizontal: 15, 
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  label: {
    fontWeight: '600',
    fontSize: 13,
    color: '#444',
  },
  value: {
    fontSize: 13,
    color: '#333',
  },
  estadoContainer: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  badgeRed: {
    backgroundColor: '#F44336',
    color: '#fff',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    fontWeight: 'bold',
    fontSize: 11,
  },
  badgeGreen: {
    backgroundColor: '#D4F4D1',
    color: '#2C6B2E',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    fontWeight: '500',
    fontSize: 12,
  },
  badgeOrange: {
    backgroundColor: '#FF7043',
    color: '#fff',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    fontWeight: 'bold',
    fontSize: 11,
  },
  iconPlaceholder: {
    fontSize: 15,
  },
  downloadLink: {
    color: '#2E4C85',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    fontSize: 13,
  },
  
});
